### ISSUE TITLE
Can`t join conference

### ISSUE THREAD

**Issue by mastershaig** [VSpectrum/web-conference#1]
When I join a conference on [https://conference.veydh.com](https://conference.veydh.com) there are below errors in console:

```
`conferencesetup.js:160 Uncaught TypeError: Cannot set property 'onclick' of null

https://conference.veydh.com:8888/socket.io/1/?t=1471540282782 Failed to load resource: net::ERR_CONNECTION_REFUSED`
```

Can you help please ?

**Comment by VSpectrum** [comment]
The node.js server that manages sessions (signaler-ssl-js) was down. I just put it back up and port 8888 is open now. 
Also, this is an old repo for the site due to a change of requirements with WebRTC: recently it was a [requirement](http://www.tokbox.com/blog/the-impact-of-googles-new-chrome-security-policy-on-webrtc/) that WebRTC had to be used over HTTPS so this repo:
https://github.com/VSpectrum/VideoConferencingWebsite would be a functioning version of the project, though you will have to get SSL certificates to use this solution

**Comment by mastershaig** [comment]
Thank you for your reply  but now login and registration not working !

**Comment by VSpectrum** [comment]
That ended up being a write permissions issue. Had to chmod 777 the database's parent directory.
